#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
# $scripts/launch_waybar &
waybar &
$scripts/tools/dynamic &

# wallpaper
$scripts/wall ~/wallpapers/gruv/gruv-place.png &

# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# old jazz
if ! pgrep -x 'pa-applet' > /dev/null
then
    pa-applet --disable-notifications &
fi

blueman-applet &
nm-applet &
pactl load-module module-bluetooth-discover #fixes bluetooth shit
# xbindkeys
