#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
# dunst & 
# AGS Version:
gnome-keyring-daemon --start --components=secrets &

# waybar &
# $scripts/tools/dynamic &

# wallpaper
$scripts/wall ~/wallpapers/gruv/gruv-place.png &

# eww daemon
# eww daemon &
# Ags version:
swww kill
swww init
ags &

# effects
# $scripts/rgb &

# other
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &


/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
swayidle -w timeout 300 'swaylock -f' before-sleep 'swaylock -f' &
swayidle -w timeout 450 'pidof java || systemctl suspend' &
dbus-update-activation-environment --all &
sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk


# old jazz
if ! pgrep -x 'pa-applet' > /dev/null
then
    pa-applet --disable-notifications &
fi

blueman-applet &
nm-applet &
pactl load-module module-bluetooth-discover #fixes bluetooth shit
# xbindkeys
#
sleep 1
way-displays > "/tmp/way-displays.${XDG_VTNR}.${USER}.log" 2>&1

