[pyprland]
plugins = [
    "scratchpads"
]

[scratchpads.spotify]
command = "spotify"
animation = "fromBottom"
class = "Spotify"
# class_match = true
# process_tracking = false
size = "75% 75%"
# max_size = "1920px 100%"
# position = "100% 10%"

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
# size = "75% 75%"
# max_size = "1920px 100%"
# margin = 100


[scratchpads.calc]
animation = "fromTop"
command = "qalculate-gtk"
class = "qalculate-gtk"
size = "60% 60%"
max_size = "1920px 100%"
margin = 100
