require "adi.options"
require "adi.plugins"
require "adi.keymaps"
require "adi.lualine"
-- require "adi.lsp"
require "adi.colorscheme"
require "adi.cmp"
require "adi.telescope"
require "adi.ufo"
require "adi.navic"
require "adi.mason"
-- require "adi.dressing"
require "adi.noice"
require "adi.treesitter"
require "adi.vimtex"
require "adi.autopairs"
require "adi.nvim-tree"
require "adi.bufferline"
--require "adi.impatient"
require "adi.alpha"
-- require "adi.dap"
-- require "adi.null-ls"
require "adi.comment"
require "adi.indent"
require "adi.whichkey"
require "adi.luasnip"
-- require "adi.auto_windows"
require "adi.flash"
-- require "adi.mini"
-- require "adi.zippy"
require "adi.scrollbar"
require "adi.paint"
-- require "adi.latex"
-- require "adi.lsplines"
require "adi.colorizer"
require "adi.gitsigns"
-- require "adi.zenmode"
require "adi.useless"
require "adi.range"
require "adi.presence"
require "adi.neogen"
require "adi.neoclip"
-- require "adi.dropbar"
-- require "adi.silicon"
